insert into user(username,password,name,email) values ('dreamboy','password','조형규','dreamboy@miraesoft.kr')
insert into user(username,password,name,email) values ('tyche','password','디케','tyche77@gmail.com')
insert into user(username,password,name,email) values ('saemi','password','새미','test@saemi.com')
insert into user(username,password,name,email) values ('geric','password','정보원','test@geric.net')
insert into user(username,password,name,email) values ('lms','password','사이버학습','test@lms.com')